<?
// Set page title.
$this->headTitle($this->translate('About'));
?>
<div id="aboutPage">
    <h1><?= $this->transEsc('Imprint') ?></h1>
    <h2>Angaben gem&auml;&szlig; &sect; 5 TMG:</h2>
    <p>i.d.a.-Dachverband e. V.<br />
        c/o Spinnboden Lesbenarchiv und Bibliothek e.V<br />
        Anklamer Stra&szlig;e 38<br />
        10115 Berlin </p>
    <h2>Vertreten durch:</h2>
    <p>Sabine Balke<br />
        Susanne Knoblich<br />
        Margit Hauser
    </p>
    <h2>Kontakt:</h2>
    <table>
        <tr> <td>Telefon:</td> <td>03052667991</td></tr>
        <tr><td>E-Mail:</td><td>kontakt@ida-dachverband.de</td> </tr>
    </table>
    <h2>Registereintrag:</h2>
    <p>Eintragung im
        Vereinsregister. <br />Registergericht:Amtsgericht Bonn <br />Registernummer: 6893
    </p>
    <p>&nbsp;</p>

    <h1><?= $this->transEsc('Disclaimer') ?></h1>
    <h2>Haftung f&uuml;r Inhalte</h2>
    <p>Als
        Diensteanbieter sind wir gem&auml;&szlig; &sect; 7 Abs.1 TMG f&uuml;r eigene Inhalte auf diesen Seiten nach
        den allgemeinen Gesetzen verantwortlich. Nach &sect;&sect; 8 bis 10 TMG sind wir als Diensteanbieter jedoch
        nicht verpflichtet, &uuml;bermittelte oder gespeicherte fremde Informationen zu &uuml;berwachen oder nach
        Umst&auml;nden zu forschen, die auf eine rechtswidrige T&auml;tigkeit hinweisen. Verpflichtungen zur
        Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon
        unber&uuml;hrt. Eine diesbez&uuml;gliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer
        konkreten Rechtsverletzung m&ouml;glich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden
        wir diese Inhalte umgehend entfernen.
    </p>
    <h2>Haftung f&uuml;r Links</h2>
    <p>Unser
        Angebot enth&auml;lt Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb
        k&ouml;nnen wir f&uuml;r diese fremden Inhalte auch keine Gew&auml;hr &uuml;bernehmen. F&uuml;r die
        Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die
        verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf m&ouml;gliche Rechtsverst&ouml;&szlig;e
        &uuml;berpr&uuml;ft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine
        permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer
        Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links
        umgehend entfernen.
    </p>
    <h2>Urheberrecht</h2>
    <p>Die durch die Seitenbetreiber erstellten
        Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielf&auml;ltigung,
        Bearbeitung, Verbreitung und jede Art der Verwertung au&szlig;erhalb der Grenzen des Urheberrechtes
        bed&uuml;rfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser
        Seite sind nur f&uuml;r den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite
        nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte
        Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden,
        bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige
        Inhalte umgehend entfernen.
    </p>

    <p>&nbsp;</p>

    <h1><?= $this->transEsc('Privacy protection') ?></h1>

    <h2>Datenschutz</h2>
    <p>Die Betreiber dieser
        Seiten nehmen den Schutz Ihrer pers&ouml;nlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen
        Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser
        Datenschutzerkl&auml;rung.
    </p>
    <p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe
        personenbezogener Daten m&ouml;glich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise
        Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies, soweit m&ouml;glich, stets auf freiwilliger
        Basis. Diese Daten werden ohne Ihre ausdr&uuml;ckliche Zustimmung nicht an Dritte weitergegeben.
    </p>
    <p>Wir weisen darauf hin, dass die Daten&uuml;bertragung im Internet (z.B. bei der Kommunikation per E-Mail)
        Sicherheitsl&uuml;cken aufweisen kann. Ein l&uuml;ckenloser Schutz der Daten vor dem Zugriff durch Dritte ist
        nicht m&ouml;glich.
    </p>
    <h2>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Piwik</h2>
    <p>Diese Website benutzt den Open Source Webanalysedienst Piwik. Piwik verwendet sog.
        "Cookies". Das sind Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der
        Benutzung der Website durch Sie erm&ouml;glichen. Dazu werden die durch den Cookie erzeugten
        Informationen &uuml;ber die Benutzung dieser Website auf unserem Server gespeichert. Die IP-Adresse wird
        vor der Speicherung anonymisiert.
    </p>
    <p>Die durch den Cookie erzeugten Informationen &uuml;ber die
        Benutzung dieser Website werden nicht an Dritte weitergegeben. Sie k&ouml;nnen die Speicherung der Cookies
        durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass
        Sie in diesem Fall gegebenenfalls nicht s&auml;mtliche Funktionen dieser Website vollumf&auml;nglich werden
        nutzen k&ouml;nnen.
    </p>
    <p>Wenn Sie mit der Speicherung und Nutzung Ihrer Daten nicht einverstanden sind,
        k&ouml;nnen Sie die Speicherung und Nutzung hier deaktivieren. In diesem Fall wird in Ihrem Browser ein Opt-
        Out-Cookie hinterlegt der verhindert, dass Piwik Nutzungsdaten speichert. Wenn Sie Ihre Cookies l&ouml;schen
        hat dies zur Folge, dass auch das Piwik Opt-Out-Cookie gel&ouml;scht wird. Das Opt-Out muss bei einem
        erneuten Beuch unserer Seite wieder aktiviert werden.
    </p>
    <p>
        <iframe frameborder="no" width="100%" height="120px"
                src="http://stats.ida-dachverband.de/index.php?module=CoreAdminHome&action=optOut&language=de">
        </iframe>
    </p>
    <h2>Cookies</h2>
    <p>Die Internetseiten verwenden teilweise so genannte Cookies. Cookies richten auf Ihrem Rechner keinen
        Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und
        sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr
        Browser speichert.
    </p>
    <p>Die meisten der von uns verwendeten Cookies sind so genannte &bdquo;Session-
        Cookies&ldquo;. Sie werden nach Ende Ihres Besuchs automatisch gel&ouml;scht. Andere Cookies bleiben auf
        Ihrem Endger&auml;t gespeichert, bis Sie diese l&ouml;schen. Diese Cookies erm&ouml;glichen es uns, Ihren
        Browser beim n&auml;chsten Besuch wiederzuerkennen.
    </p>
    <p>Sie k&ouml;nnen Ihren Browser so einstellen,
        dass Sie &uuml;ber das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die
        Annahme von Cookies f&uuml;r bestimmte F&auml;lle oder generell ausschlie&szlig;en sowie das automatische
        L&ouml;schen der Cookies beim Schlie&szlig;en des Browser aktivieren. Bei der Deaktivierung von Cookies
        kann die Funktionalit&auml;t dieser Website eingeschr&auml;nkt sein.
    </p>
    <h2>Server-Log-Files</h2>
    <p>Der Provider der Seiten erhebt und speichert automatisch Informationen in so
        genannten Server-Log Files, die Ihr Browser automatisch an uns &uuml;bermittelt. Dies sind:
    </p>
    <ul>
        <li>Browsertyp/ Browserversion</li>
        <li>verwendetes Betriebssystem</li>
        <li>Referrer URL</li>
        <li>Hostname des zugreifenden Rechners</li>
        <li>Uhrzeit der Serveranfrage</li>
    </ul>
    <p>Diese Daten sind nicht
        bestimmten Personen zuordenbar. Eine Zusammenf&uuml;hrung dieser Daten mit anderen Datenquellen wird
        nicht vorgenommen. Wir behalten uns vor, diese Daten nachtr&auml;glich zu pr&uuml;fen, wenn uns konkrete
        Anhaltspunkte f&uuml;r eine rechtswidrige Nutzung bekannt werden.
    </p>
    <h2>Einbindung von Diensten und Inhalten Dritter</h2>
    <p>
        Es kann vorkommen, dass innerhalb dieses Onlineangebotes Inhalte Dritter, wie zum Beispiel Videos von YouTube,
        Kartenmaterial von Google-Maps, RSS-Feeds oder Grafiken von anderen Webseiten eingebunden werden. Dies setzt
        immer voraus, dass die Anbieter dieser Inhalte (nachfolgend bezeichnet als "Dritt-Anbieter") die IP-Adresse
        der Nutzer wahr nehmen. Denn ohne die IP-Adresse, könnten sie die Inhalte nicht an den Browser des jeweiligen
        Nutzers senden. Die IP-Adresse ist damit für die Darstellung dieser Inhalte erforderlich. Wir bemühen uns nur
        solche Inhalte zu verwenden, deren jeweilige Anbieter die IP-Adresse lediglich zur Auslieferung der Inhalte
        verwenden. Jedoch  haben wir keinen Einfluss darauf, falls die Dritt-Anbieter die IP-Adresse z.B. für
        statistische Zwecke speichern. Soweit dies uns bekannt ist, klären wir die Nutzer darüber auf.
    </p>
</div>