<?
// Set up standard record scripts:
$this->headScript()->appendFile("record.js");
$this->headScript()->appendFile("check_save_statuses.js");
$this->headScript()->appendFile("map.js");
$this->headScript()->appendFile("https://maps.googleapis.com/maps/api/js?language=de&key=AIzaSyAoK_7LQ3D0oMjok03vxB50LXe37yKlteE");

// Activate Syndetics Plus if necessary:
if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
}

// Add RDF header link if applicable:
if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
}

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
$this->layout()->title = $this->driver->getShortTitle();

// Get institution details
$institution = reset($this->driver->getInstitutions());
$userLanguage = $this->plugin('translate')->getTranslator()->getLocale();
$institutionDetails = $this->driver->getInstitutionDetails($institution, $userLanguage);

?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<div class="col-md-9">
    <div class="record recordId source<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" id="record">
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" class="hiddenId" id="record_id"/>
        <input type="hidden" value="<?= $this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource"/>
        <?= $this->flashmessages() ?>
        <?= $this->record($this->driver)->getCoreMetadata() ?>
    </div>

      <div class="record row detail-view-detail-row">
        <?php $tabCount = 0; ?>
        <?php foreach ($this->tabs as $tab => $obj): ?>
            <div class="col-sm-6">
                <?php if ($tab == "Description") : ?>
                    <h4 data-section-toggle="true" id="tabnav"><?php echo $this->transEsc('further information'); ?></h4>
                <?php elseif ($tab == "HierarchyTree") : ?>
                    <h4 data-section-toggle="true"><?php if ($this->driver->isArchive()): ?>
                    		<?php echo $this->transEsc('Tectonic'); ?>
                    	<?php else : ?>
                    		<?php echo $this->transEsc('Context'); ?>
                    	<?php endif;?>
                    </h4>
                <?php elseif ($tab == "OtherInstitutions") : ?>
                	<h4 data-section-toggle="true"><?php echo $this->transEsc('Also available in other institutions'); ?></h4>
                <?php endif; ?>
                <div class="collapsible">
                    <?php echo $this->record($this->driver)->getTab($obj) ?>
                </div>
            </div>
            <?php $tabCount++; ?>
        <?php endforeach; ?>

    <?php /* PHE - START start next row, if previous row is full */ ?>
    <?php if ($institutionDetails != NULL && $tabCount > 1 && $tabCount % 2 == 0) : ?>
    </div><div class="record row detail-view-detail-row">
    <? endif; ?>
    <?php /* PHE - END start next row, if previous row is full */ ?>
        <?php /* PHE - START of the institution details */ ?>
        <?php if ($institutionDetails != NULL) : ?>
            <?php $institutionName = isset($institutionDetails["name"]) ? $institutionDetails["name"] : $institution; ?>
            <div class="col-sm-6 institution detail-view-detail-row">
                <h4 data-section-toggle="true" data-toggle-yyy="mapyyy">
		    <a name="link"></a>
                    <?php echo $this->transEsc('Location'); ?>
                </h4>
                <div class="collapsible">
                    <h5><?= strip_tags($institutionName, "<br>"); ?></h5>
                    <?php if (isset($institutionDetails["street"])) : ?>
                        <div id="institution-address"><?= strip_tags($institutionDetails["street"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["city"])) : ?>
                        <div id="institution-address"><?= strip_tags($institutionDetails["city"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["addressExtra"])) : ?>
                        <div class="address-extra"><?= strip_tags($institutionDetails["addressExtra"], '<br><strong><a>'); ?>&nbsp;<i class="fa fa-external-link"></i><br /><br /></div>
                    <?php endif; ?>
                    <?php if (isset($institutionDetails["openingHours"])) : ?>
                        <div class="opening-hours"><?= strip_tags($institutionDetails["openingHours"], '<br><strong><a>'); ?></div>
                    <?php endif; ?>
                    <!-- Start google maps -->
                    <?php if (isset($institutionDetails["latitude"]) && isset($institutionDetails["longitude"])) : ?>
                        <div id="map-canvas"></div>
                        <script>
                        	$(document).ready(initMap('map-canvas',
                        			<?= (float) $institutionDetails["latitude"]; ?>,
                        			<?= (float) $institutionDetails["longitude"]; ?>));
                        </script>
                    <?php endif; ?>
                    <!-- END google maps -->
                </div>
            </div>
        <?php endif; ?>
    </div>
    
</div>
<div class="sidebar col-md-3 hidden-print detail-view-sidebar" data-sidebar-toggle="true">
	<h4><?=$this->transEsc('Location'); ?></h4>
	<div class="collapsible">
		<h5><a href="#link"><?= strip_tags($institutionName, "<br>"); ?></a></h5>
        <?php if (isset($institutionDetails["street"])) : ?>
        	<div id="institution-address"><?= strip_tags($institutionDetails["street"]) ; 
		        if (isset($institutionDetails["street2"])) : 
		        ?>, <?= strip_tags($institutionDetails["street2"]) ; ?>
		        <?php endif; ?>, <?= strip_tags($institutionDetails["city"]) ; ?>
        	</div>
        <?php endif; ?>
        <!-- Start google maps -->
        <?php if (isset($institutionDetails["latitude"]) && isset($institutionDetails["longitude"])) : ?>
        	<a href="#link"><img id ="small-map" alt="Karte" src=""></a>
        	<script type="text/javascript">
        		$(document).ready(initStaticMap('small-map',
        			<?= (float) $institutionDetails["latitude"]; ?>,
        			<?= (float) $institutionDetails["longitude"]; ?>,
        			"<?=  $this->driver->getServerUrl()?>"));
        	</script>
         <?php endif; ?>
         <!-- END google maps -->
	</div>
</div>
<div class="sidebar col-md-3 hidden-print detail-view-sidebar" data-sidebar-toggle="true">
    <?php foreach ($this->related()->getList($this->driver) as $current): ?>
        <?= $this->related()->render($current) ?>
    <?php endforeach; ?>
</div>